### ISSUE TITLE
Unsupported format character 'B'

### ISSUE THREAD

**Issue by pypingou** [fedora-infra/anitya#124]
````
Text-Tabs+Wrap
Traceback (most recent call last):
  File "/usr/share/anitya/anitya_cron.py", line 70, in <module>
    main(debug=debug)
  File "/usr/share/anitya/anitya_cron.py", line 58, in main
    anitya.check_release(project, session)
  File "/usr/lib/python2.7/site-packages/anitya/__init__.py", line 60, in check_release
    up_version = backend.get_version(project)
  File "/usr/lib/python2.7/site-packages/anitya/lib/backends/custom.py", line 48, in get_version
    return cls.get_ordered_versions(project)[-1]
  File "/usr/lib/python2.7/site-packages/anitya/lib/backends/__init__.py", line 219, in get_ordered_versions
    vlist = self.get_versions(project)
  File "/usr/lib/python2.7/site-packages/anitya/lib/backends/custom.py", line 70, in get_versions
    regex = regex % {'name': project.name.replace('+', '\+')}
ValueError: unsupported format character 'B' (0x42) at index 11
````

**Comment by pypingou** [comment]
Fixed in https://github.com/fedora-infra/anitya/pull/125
