### ISSUE TITLE
Internal server errors occurring at release-monitoring

### ISSUE THREAD

**Issue by heitbaum** [fedora-infra/anitya#1390]
Examples:
https://release-monitoring.org/project/1181/
SDL2
lz4
p7zip
rsyslog

**Comment by Zlopez** [comment]
Here is the error that is happening when opening the project:
```
[Mon Jun 27 14:30:39.628198 2022] [wsgi:error] [pid 2921:tid 2931] [client 10.131.0.1:40892] [2022-06-27 14:30:39,627 anitya.app ERROR] Exception on /project/1181/ [GET], referer: https://github.com/
[Mon Jun 27 14:30:39.628236 2022] [wsgi:error] [pid 2921:tid 2931] [client 10.131.0.1:40892] Traceback (most recent call last):, referer: https://github.com/
[Mon Jun 27 14:30:39.628239 2022] [wsgi:error] [pid 2921:tid 2931] [client 10.131.0.1:40892] File "/usr/lib/python3.10/site-packages/flask/app.py", line 2073, in wsgi_app, referer: https://github.com/
[Mon Jun 27 14:30:39.628241 2022] [wsgi:error] [pid 2921:tid 2931] [client 10.131.0.1:40892] response = self.full_dispatch_request(), referer: https://github.com/
[Mon Jun 27 14:30:39.628244 2022] [wsgi:error] [pid 2921:tid 2931] [client 10.131.0.1:40892] File "/usr/lib/python3.10/site-packages/flask/app.py", line 1518, in full_dispatch_request, referer: https://github.com/
[Mon Jun 27 14:30:39.628246 2022] [wsgi:error] [pid 2921:tid 2931] [client 10.131.0.1:40892] rv = self.handle_user_exception(e), referer: https://github.com/
[Mon Jun 27 14:30:39.628248 2022] [wsgi:error] [pid 2921:tid 2931] [client 10.131.0.1:40892] File "/usr/lib/python3.10/site-packages/flask/app.py", line 1516, in full_dispatch_request, referer: https://github.com/
[Mon Jun 27 14:30:39.628250 2022] [wsgi:error] [pid 2921:tid 2931] [client 10.131.0.1:40892] rv = self.dispatch_request(), referer: https://github.com/
[Mon Jun 27 14:30:39.628252 2022] [wsgi:error] [pid 2921:tid 2931] [client 10.131.0.1:40892] File "/usr/lib/python3.10/site-packages/flask/app.py", line 1502, in dispatch_request, referer: https://github.com/
[Mon Jun 27 14:30:39.628254 2022] [wsgi:error] [pid 2921:tid 2931] [client 10.131.0.1:40892] return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args), referer: https://github.com/
[Mon Jun 27 14:30:39.628257 2022] [wsgi:error] [pid 2921:tid 2931] [client 10.131.0.1:40892] File "/usr/local/lib/python3.10/site-packages/anitya/ui.py", line 111, in project, referer: https://github.com/
[Mon Jun 27 14:30:39.628264 2022] [wsgi:error] [pid 2921:tid 2931] [client 10.131.0.1:40892] return flask.render_template("project.html", current="project", project=project), referer: https://github.com/
[Mon Jun 27 14:30:39.628267 2022] [wsgi:error] [pid 2921:tid 2931] [client 10.131.0.1:40892] File "/usr/lib/python3.10/site-packages/flask/templating.py", line 147, in render_template, referer: https://github.com/
[Mon Jun 27 14:30:39.628269 2022] [wsgi:error] [pid 2921:tid 2931] [client 10.131.0.1:40892] return _render(, referer: https://github.com/
[Mon Jun 27 14:30:39.628271 2022] [wsgi:error] [pid 2921:tid 2931] [client 10.131.0.1:40892] File "/usr/lib/python3.10/site-packages/flask/templating.py", line 128, in _render, referer: https://github.com/
[Mon Jun 27 14:30:39.628273 2022] [wsgi:error] [pid 2921:tid 2931] [client 10.131.0.1:40892] rv = template.render(context), referer: https://github.com/
[Mon Jun 27 14:30:39.628275 2022] [wsgi:error] [pid 2921:tid 2931] [client 10.131.0.1:40892] File "/usr/lib/python3.10/site-packages/jinja2/environment.py", line 1291, in render, referer: https://github.com/
[Mon Jun 27 14:30:39.628277 2022] [wsgi:error] [pid 2921:tid 2931] [client 10.131.0.1:40892] self.environment.handle_exception(), referer: https://github.com/
[Mon Jun 27 14:30:39.628279 2022] [wsgi:error] [pid 2921:tid 2931] [client 10.131.0.1:40892] File "/usr/lib/python3.10/site-packages/jinja2/environment.py", line 925, in handle_exception, referer: https://github.com/
[Mon Jun 27 14:30:39.628282 2022] [wsgi:error] [pid 2921:tid 2931] [client 10.131.0.1:40892] raise rewrite_traceback_stack(source=source), referer: https://github.com/
[Mon Jun 27 14:30:39.628284 2022] [wsgi:error] [pid 2921:tid 2931] [client 10.131.0.1:40892] File "/usr/local/lib/python3.10/site-packages/anitya/templates/project.html", line 1, in top-level template code, referer: https://github.com/
[Mon Jun 27 14:30:39.628286 2022] [wsgi:error] [pid 2921:tid 2931] [client 10.131.0.1:40892] {% extends "master.html" %}, referer: https://github.com/
[Mon Jun 27 14:30:39.628288 2022] [wsgi:error] [pid 2921:tid 2931] [client 10.131.0.1:40892] File "/usr/local/lib/python3.10/site-packages/anitya/templates/master.html", line 189, in top-level template code, referer: https://github.com/
[Mon Jun 27 14:30:39.628291 2022] [wsgi:error] [pid 2921:tid 2931] [client 10.131.0.1:40892] {% block body %}{% endblock %}, referer: https://github.com/
[Mon Jun 27 14:30:39.628293 2022] [wsgi:error] [pid 2921:tid 2931] [client 10.131.0.1:40892] File "/usr/local/lib/python3.10/site-packages/anitya/templates/project.html", line 49, in block 'body', referer: https://github.com/
[Mon Jun 27 14:30:39.628295 2022] [wsgi:error] [pid 2921:tid 2931] [client 10.131.0.1:40892] {% if project.versions %}, referer: https://github.com/
[Mon Jun 27 14:30:39.628297 2022] [wsgi:error] [pid 2921:tid 2931] [client 10.131.0.1:40892] File "/usr/lib/python3.10/site-packages/jinja2/environment.py", line 474, in getattr, referer: https://github.com/
[Mon Jun 27 14:30:39.628299 2022] [wsgi:error] [pid 2921:tid 2931] [client 10.131.0.1:40892] return getattr(obj, attribute), referer: https://github.com/
[Mon Jun 27 14:30:39.628301 2022] [wsgi:error] [pid 2921:tid 2931] [client 10.131.0.1:40892] File "/usr/local/lib/python3.10/site-packages/anitya/db/models.py", line 293, in versions, referer: https://github.com/
[Mon Jun 27 14:30:39.628303 2022] [wsgi:error] [pid 2921:tid 2931] [client 10.131.0.1:40892] sorted_versions = self.get_sorted_version_objects(), referer: https://github.com/
[Mon Jun 27 14:30:39.628305 2022] [wsgi:error] [pid 2921:tid 2931] [client 10.131.0.1:40892] File "/usr/local/lib/python3.10/site-packages/anitya/db/models.py", line 404, in get_sorted_version_objects, referer: https://github.com/
[Mon Jun 27 14:30:39.628307 2022] [wsgi:error] [pid 2921:tid 2931] [client 10.131.0.1:40892] sorted_versions = list(reversed(sorted(versions))), referer: https://github.com/
[Mon Jun 27 14:30:39.628311 2022] [wsgi:error] [pid 2921:tid 2931] [client 10.131.0.1:40892] File "/usr/local/lib/python3.10/site-packages/anitya/lib/versions/rpm.py", line 175, in __lt__, referer: https://github.com/
[Mon Jun 27 14:30:39.628314 2022] [wsgi:error] [pid 2921:tid 2931] [client 10.131.0.1:40892] result = _compare_rpm_labels((None, v1, None), (None, v2, None)), referer: https://github.com/
[Mon Jun 27 14:30:39.628316 2022] [wsgi:error] [pid 2921:tid 2931] [client 10.131.0.1:40892] ValueError: invalid version, referer: https://github.com/
```

**Comment by legoktm** [comment]
Another example: https://release-monitoring.org/project/192663/ / https://release-monitoring.org/api/v2/versions/?project_id=192663

**Comment by Zlopez** [comment]
Even with the fix above the issue is still happening.

**Comment by legoktm** [comment]
Thank you!
