### ISSUE TITLE
Python versioning parse doesn't return string

### ISSUE THREAD

**Issue by Zlopez** [fedora-infra/anitya#1402]
New python versioning scheme returns some special version object instead of string. This is causing the following issue:
```
(psycopg2.ProgrammingError) can't adapt type 'Version'
[SQL: UPDATE projects SET latest_version=%(latest_version)s, updated_on=CURRENT_TIMESTAMP WHERE projects.id = %(projects_id)s]
[parameters: {'latest_version': <Version('0.8.2')>, 'projects_id': 83548}]
(Background on this error at: https://sqlalche.me/e/14/f405)
Traceback (most recent call last):
File "/usr/lib64/python3.10/site-packages/sqlalchemy/engine/base.py", line 1819, in _execute_context
self.dialect.do_execute(
File "/usr/lib64/python3.10/site-packages/sqlalchemy/engine/default.py", line 732, in do_execute
cursor.execute(statement, parameters)
psycopg2.ProgrammingError: can't adapt type 'Version'
```

The `parse` method from `BaseVersion` shouldn't be overloaded and instead these conversions should be done inside the compare methods.

**Comment by nikitabugrovsky** [comment]
@Zlopez could you please review submitted bug fix?
