### ISSUE TITLE
Fix user  Authentication error when on localhost

### ISSUE THREAD

**Issue by NyuydineBill** [fedora-infra/anitya#1723]
After setting up the project on your local machine, you will realize that, you need to be logged in before add a project or any other feature. Now as a sample, it should work like this [https://release-monitoring.org/](https://release-monitoring.org/). 
But on the contrary you will receive several errors, and get this message on terminal console

```
[anitya.app ERROR] Exception on /login/fedora/ [GET]
Traceback (most recent call last):
  File "/home/nyuydinebill/.cache/pypoetry/virtualenvs/anitya-8dx-Zgie-py3.10/lib/python3.10/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/nyuydinebill/.cache/pypoetry/virtualenvs/anitya-8dx-Zgie-py3.10/lib/python3.10/site-packages/flask/app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/nyuydinebill/.cache/pypoetry/virtualenvs/anitya-8dx-Zgie-py3.10/lib/python3.10/site-packages/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/nyuydinebill/.cache/pypoetry/virtualenvs/anitya-8dx-Zgie-py3.10/lib/python3.10/site-packages/flask/app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/home/nyuydinebill/.cache/pypoetry/virtualenvs/anitya-8dx-Zgie-py3.10/lib/python3.10/site-packages/social_flask/utils.py", line 43, in wrapper
    return func(backend, *args, **kwargs)
  File "/home/nyuydinebill/.cache/pypoetry/virtualenvs/anitya-8dx-Zgie-py3.10/lib/python3.10/site-packages/social_flask/routes.py", line 14, in auth
    return do_auth(g.backend)
  File "/home/nyuydinebill/.cache/pypoetry/virtualenvs/anitya-8dx-Zgie-py3.10/lib/python3.10/site-packages/social_core/actions.py", line 29, in do_auth
    return backend.start()
  File "/home/nyuydinebill/.cache/pypoetry/virtualenvs/anitya-8dx-Zgie-py3.10/lib/python3.10/site-packages/social_core/backends/base.py", line 34, in start
    if self.uses_redirect():
  File "/home/nyuydinebill/.cache/pypoetry/virtualenvs/anitya-8dx-Zgie-py3.10/lib/python3.10/site-packages/social_core/backends/open_id.py", line 233, in uses_redirect
    return self.openid_request().shouldSendRedirect()
  File "/home/nyuydinebill/.cache/pypoetry/virtualenvs/anitya-8dx-Zgie-py3.10/lib/python3.10/site-packages/social_core/backends/open_id.py", line 238, in openid_request
    return self.consumer().begin(url_add_parameters(self.openid_url(),
  File "/home/nyuydinebill/.cache/pypoetry/virtualenvs/anitya-8dx-Zgie-py3.10/lib/python3.10/site-packages/openid/consumer/consumer.py", line 360, in begin
    return self.beginWithoutDiscovery(service, anonymous)
  File "/home/nyuydinebill/.cache/pypoetry/virtualenvs/anitya-8dx-Zgie-py3.10/lib/python3.10/site-packages/openid/consumer/consumer.py", line 383, in beginWithoutDiscovery
    auth_req = self.consumer.begin(service)
  File "/home/nyuydinebill/.cache/pypoetry/virtualenvs/anitya-8dx-Zgie-py3.10/lib/python3.10/site-packages/openid/consumer/consumer.py", line 611, in begin
    assoc = self._getAssociation(service_endpoint)
  File "/home/nyuydinebill/.cache/pypoetry/virtualenvs/anitya-8dx-Zgie-py3.10/lib/python3.10/site-packages/openid/consumer/consumer.py", line 1184, in _getAssociation
    self.store.storeAssociation(endpoint.server_url, assoc)
  File "/home/nyuydinebill/.cache/pypoetry/virtualenvs/anitya-8dx-Zgie-py3.10/lib/python3.10/site-packages/social_core/store.py", line 21, in storeAssociation
    self.assoc.store(server_url, association)
  File "/home/nyuydinebill/.cache/pypoetry/virtualenvs/anitya-8dx-Zgie-py3.10/lib/python3.10/site-packages/social_sqlalchemy/storage.py", line 218, in store
    assoc.secret = base64.encodestring(association.secret).decode()
AttributeError: module 'base64' has no attribute 'encodestring'
```

**Requirements**

- Configure third party packages and allow local server urls
- Fix the issue regarding the error on terminal
- 

**This will enable contributors to access the project and fix the issues they are working on**

**Comment by Zlopez** [comment]
Could you try running it in vagrant, so we can remove the possibility that it's something on your machine. See [documentation](https://anitya.readthedocs.io/en/stable/contributing.html#vagrant) for instructions.

**Comment by NyuydineBill** [comment]
I am trying to set-up vagrant environment and getting this, I have tried resolving it but, its not working
![Screenshot from 2024-03-07 12-53-03](https://github.com/fedora-infra/anitya/assets/121938133/7697bba9-aa63-440a-b97c-f5ba206f0109)

**Comment by Zlopez** [comment]
Did you encountered any error when running `vagrant up` ?
I'm trying to deploy it on my machine and it's failing for me.

**Comment by NyuydineBill** [comment]
> Did you encountered any error when running `vagrant up` ? I'm trying to deploy it on my machine and it's failing for me.

Yes I kept receiving errors and that was why I used Python virtualenv 
it opens the project on python venv, but then user can't authenticate and log in while on local environment

**Comment by Freedisch** [comment]
@NyuydineBill, I had the same issue with Vagrant, but I was able to run the project with docker, u should try running the project with docker it's pretty straight forward just have to run `make up` I believe you should be good to go

**Comment by NyuydineBill** [comment]
> @NyuydineBill, I had the same issue with Vagrant, but I was able to run the project with docker, u should try running the project with docker it's pretty straight forward just have to run `make up` I believe that will work

OKay @Freedisch  Thanks for reaching out
I finally resolved the issue, I have used python venv. The directions to anyone using Python virtual env and facing similar problem are in a PR just created

**Comment by Zlopez** [comment]
I'm trying to solve the error when setting up dev env. It should be solved soon.

**Comment by Zlopez** [comment]
Fixed the vagrant environment for Anitya with one bug I encountered during login.

**Comment by Zlopez** [comment]
And I fixed the container dev environment as well. [PR](https://github.com/fedora-infra/anitya/pull/1730) is here.
