### ISSUE TITLE
Distro page 500 error...

### ISSUE THREAD

**Issue by relrod** [fedora-infra/anitya#69]
After logging in and clicking the distro page I got a 500 (but it seems to be intermittent). Logs say this:

```
[Thu Dec 18 21:19:10.693286 2014] [:error] [pid 12342] Traceback (most recent call last):
[Thu Dec 18 21:19:10.693371 2014] [:error] [pid 12342]   File "/usr/lib64/python2.7/logging/handlers.py", line 929, in emit
[Thu Dec 18 21:19:10.694114 2014] [:error] [pid 12342]     msg = self.format(record)
[Thu Dec 18 21:19:10.694159 2014] [:error] [pid 12342]   File "/usr/lib64/python2.7/logging/__init__.py", line 724, in format
[Thu Dec 18 21:19:10.694205 2014] [:error] [pid 12342]     return fmt.format(record)
[Thu Dec 18 21:19:10.694224 2014] [:error] [pid 12342]   File "/usr/lib64/python2.7/logging/__init__.py", line 467, in format
[Thu Dec 18 21:19:10.694282 2014] [:error] [pid 12342]     s = self._fmt % record.__dict__
[Thu Dec 18 21:19:10.694324 2014] [:error] [pid 12342] KeyError: 'proc_name'
[Thu Dec 18 21:19:10.694338 2014] [:error] [pid 12342] Logged from file app.py, line 1423
[Thu Dec 18 21:19:10.700680 2014] [:error] [pid 12342] Exception on /distros/ [GET]
[Thu Dec 18 21:19:10.700704 2014] [:error] [pid 12342] Traceback (most recent call last):
[Thu Dec 18 21:19:10.700710 2014] [:error] [pid 12342]   File "/usr/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
[Thu Dec 18 21:19:10.700714 2014] [:error] [pid 12342]     response = self.full_dispatch_request()
[Thu Dec 18 21:19:10.700718 2014] [:error] [pid 12342]   File "/usr/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
[Thu Dec 18 21:19:10.700723 2014] [:error] [pid 12342]     rv = self.handle_user_exception(e)
[Thu Dec 18 21:19:10.700727 2014] [:error] [pid 12342]   File "/usr/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
[Thu Dec 18 21:19:10.700731 2014] [:error] [pid 12342]     reraise(exc_type, exc_value, tb)
[Thu Dec 18 21:19:10.700735 2014] [:error] [pid 12342]   File "/usr/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
[Thu Dec 18 21:19:10.700739 2014] [:error] [pid 12342]     rv = self.dispatch_request()
[Thu Dec 18 21:19:10.700743 2014] [:error] [pid 12342]   File "/usr/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
[Thu Dec 18 21:19:10.700747 2014] [:error] [pid 12342]     return self.view_functions[rule.endpoint](**req.view_args)
[Thu Dec 18 21:19:10.700751 2014] [:error] [pid 12342]   File "/usr/lib/python2.7/site-packages/anitya/ui.py", line 138, in distros
[Thu Dec 18 21:19:10.700755 2014] [:error] [pid 12342]     distros = anitya.lib.model.Distro.all(SESSION, page=page)
[Thu Dec 18 21:19:10.700759 2014] [:error] [pid 12342]   File "/usr/lib/python2.7/site-packages/anitya/lib/model.py", line 177, in all
[Thu Dec 18 21:19:10.700763 2014] [:error] [pid 12342]     return query.all()
[Thu Dec 18 21:19:10.700767 2014] [:error] [pid 12342]   File "/usr/lib64/python2.7/site-packages/sqlalchemy/orm/query.py", line 2300, in all
[Thu Dec 18 21:19:10.700771 2014] [:error] [pid 12342]     return list(self)
[Thu Dec 18 21:19:10.700775 2014] [:error] [pid 12342]   File "/usr/lib64/python2.7/site-packages/sqlalchemy/orm/query.py", line 2412, in __iter__
[Thu Dec 18 21:19:10.700779 2014] [:error] [pid 12342]     return self._execute_and_instances(context)
[Thu Dec 18 21:19:10.700783 2014] [:error] [pid 12342]   File "/usr/lib64/python2.7/site-packages/sqlalchemy/orm/query.py", line 2427, in _execute_and_instances
[Thu Dec 18 21:19:10.700787 2014] [:error] [pid 12342]     result = conn.execute(querycontext.statement, self._params)
[Thu Dec 18 21:19:10.700791 2014] [:error] [pid 12342]   File "/usr/lib64/python2.7/site-packages/sqlalchemy/engine/base.py", line 729, in execute
[Thu Dec 18 21:19:10.700795 2014] [:error] [pid 12342]     return meth(self, multiparams, params)
[Thu Dec 18 21:19:10.700799 2014] [:error] [pid 12342]   File "/usr/lib64/python2.7/site-packages/sqlalchemy/sql/elements.py", line 321, in _execute_on_connection
[Thu Dec 18 21:19:10.700804 2014] [:error] [pid 12342]     return connection._execute_clauseelement(self, multiparams, params)
[Thu Dec 18 21:19:10.700808 2014] [:error] [pid 12342]   File "/usr/lib64/python2.7/site-packages/sqlalchemy/engine/base.py", line 826, in _execute_clauseelement
[Thu Dec 18 21:19:10.700812 2014] [:error] [pid 12342]     compiled_sql, distilled_params
[Thu Dec 18 21:19:10.700815 2014] [:error] [pid 12342]   File "/usr/lib64/python2.7/site-packages/sqlalchemy/engine/base.py", line 958, in _execute_context
[Thu Dec 18 21:19:10.700819 2014] [:error] [pid 12342]     context)
[Thu Dec 18 21:19:10.700823 2014] [:error] [pid 12342]   File "/usr/lib64/python2.7/site-packages/sqlalchemy/engine/base.py", line 1160, in _handle_dbapi_exception
[Thu Dec 18 21:19:10.700827 2014] [:error] [pid 12342]     exc_info
[Thu Dec 18 21:19:10.700844 2014] [:error] [pid 12342]   File "/usr/lib64/python2.7/site-packages/sqlalchemy/util/compat.py", line 199, in raise_from_cause
[Thu Dec 18 21:19:10.700849 2014] [:error] [pid 12342]     reraise(type(exception), exception, tb=exc_tb)
[Thu Dec 18 21:19:10.700854 2014] [:error] [pid 12342]   File "/usr/lib64/python2.7/site-packages/sqlalchemy/engine/base.py", line 951, in _execute_context
[Thu Dec 18 21:19:10.700858 2014] [:error] [pid 12342]     context)
[Thu Dec 18 21:19:10.700861 2014] [:error] [pid 12342]   File "/usr/lib64/python2.7/site-packages/sqlalchemy/engine/default.py", line 436, in do_execute
[Thu Dec 18 21:19:10.700865 2014] [:error] [pid 12342]     cursor.execute(statement, parameters)
[Thu Dec 18 21:19:10.700869 2014] [:error] [pid 12342] OperationalError: (OperationalError) terminating connection due to administrator command
[Thu Dec 18 21:19:10.700873 2014] [:error] [pid 12342] FATAL:  terminating connection due to administrator command
[Thu Dec 18 21:19:10.700878 2014] [:error] [pid 12342]  'SELECT distros.name AS distros_name \\nFROM distros ORDER BY distros.name \\n LIMIT %(param_1)s OFFSET %(param_2)s' {'param_1': 50, 'param_2': 0}
[Thu Dec 18 21:19:10.701036 2014] [:error] [pid 12342] Exception on /distros/ [GET]
[Thu Dec 18 21:19:10.701055 2014] [:error] [pid 12342] Traceback (most recent call last):
[Thu Dec 18 21:19:10.701061 2014] [:error] [pid 12342]   File "/usr/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
[Thu Dec 18 21:19:10.701065 2014] [:error] [pid 12342]     response = self.full_dispatch_request()
[Thu Dec 18 21:19:10.701085 2014] [:error] [pid 12342]   File "/usr/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
[Thu Dec 18 21:19:10.701092 2014] [:error] [pid 12342]     rv = self.handle_user_exception(e)
[Thu Dec 18 21:19:10.701096 2014] [:error] [pid 12342]   File "/usr/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
[Thu Dec 18 21:19:10.701100 2014] [:error] [pid 12342]     reraise(exc_type, exc_value, tb)
[Thu Dec 18 21:19:10.701104 2014] [:error] [pid 12342]   File "/usr/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
[Thu Dec 18 21:19:10.701108 2014] [:error] [pid 12342]     rv = self.dispatch_request()
[Thu Dec 18 21:19:10.701112 2014] [:error] [pid 12342]   File "/usr/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
[Thu Dec 18 21:19:10.701116 2014] [:error] [pid 12342]     return self.view_functions[rule.endpoint](**req.view_args)
[Thu Dec 18 21:19:10.701120 2014] [:error] [pid 12342]   File "/usr/lib/python2.7/site-packages/anitya/ui.py", line 138, in distros
[Thu Dec 18 21:19:10.701124 2014] [:error] [pid 12342]     distros = anitya.lib.model.Distro.all(SESSION, page=page)
[Thu Dec 18 21:19:10.701128 2014] [:error] [pid 12342]   File "/usr/lib/python2.7/site-packages/anitya/lib/model.py", line 177, in all
[Thu Dec 18 21:19:10.701132 2014] [:error] [pid 12342]     return query.all()
[Thu Dec 18 21:19:10.701136 2014] [:error] [pid 12342]   File "/usr/lib64/python2.7/site-packages/sqlalchemy/orm/query.py", line 2300, in all
[Thu Dec 18 21:19:10.701140 2014] [:error] [pid 12342]     return list(self)
[Thu Dec 18 21:19:10.701143 2014] [:error] [pid 12342]   File "/usr/lib64/python2.7/site-packages/sqlalchemy/orm/query.py", line 2412, in __iter__
[Thu Dec 18 21:19:10.701147 2014] [:error] [pid 12342]     return self._execute_and_instances(context)
[Thu Dec 18 21:19:10.701151 2014] [:error] [pid 12342]   File "/usr/lib64/python2.7/site-packages/sqlalchemy/orm/query.py", line 2427, in _execute_and_instances
[Thu Dec 18 21:19:10.701155 2014] [:error] [pid 12342]     result = conn.execute(querycontext.statement, self._params)
[Thu Dec 18 21:19:10.701159 2014] [:error] [pid 12342]   File "/usr/lib64/python2.7/site-packages/sqlalchemy/engine/base.py", line 729, in execute
[Thu Dec 18 21:19:10.701163 2014] [:error] [pid 12342]     return meth(self, multiparams, params)
[Thu Dec 18 21:19:10.701179 2014] [:error] [pid 12342]   File "/usr/lib64/python2.7/site-packages/sqlalchemy/sql/elements.py", line 321, in _execute_on_connection
[Thu Dec 18 21:19:10.701185 2014] [:error] [pid 12342]     return connection._execute_clauseelement(self, multiparams, params)
[Thu Dec 18 21:19:10.701189 2014] [:error] [pid 12342]   File "/usr/lib64/python2.7/site-packages/sqlalchemy/engine/base.py", line 826, in _execute_clauseelement
[Thu Dec 18 21:19:10.701194 2014] [:error] [pid 12342]     compiled_sql, distilled_params
[Thu Dec 18 21:19:10.701197 2014] [:error] [pid 12342]   File "/usr/lib64/python2.7/site-packages/sqlalchemy/engine/base.py", line 958, in _execute_context
[Thu Dec 18 21:19:10.701201 2014] [:error] [pid 12342]     context)
[Thu Dec 18 21:19:10.701205 2014] [:error] [pid 12342]   File "/usr/lib64/python2.7/site-packages/sqlalchemy/engine/base.py", line 1160, in _handle_dbapi_exception
[Thu Dec 18 21:19:10.701209 2014] [:error] [pid 12342]     exc_info
[Thu Dec 18 21:19:10.701212 2014] [:error] [pid 12342]   File "/usr/lib64/python2.7/site-packages/sqlalchemy/util/compat.py", line 199, in raise_from_cause
[Thu Dec 18 21:19:10.701216 2014] [:error] [pid 12342]     reraise(type(exception), exception, tb=exc_tb)
[Thu Dec 18 21:19:10.701220 2014] [:error] [pid 12342]   File "/usr/lib64/python2.7/site-packages/sqlalchemy/engine/base.py", line 951, in _execute_context
[Thu Dec 18 21:19:10.701224 2014] [:error] [pid 12342]     context)
[Thu Dec 18 21:19:10.701228 2014] [:error] [pid 12342]   File "/usr/lib64/python2.7/site-packages/sqlalchemy/engine/default.py", line 436, in do_execute
[Thu Dec 18 21:19:10.701232 2014] [:error] [pid 12342]     cursor.execute(statement, parameters)
[Thu Dec 18 21:19:10.701235 2014] [:error] [pid 12342] OperationalError: (OperationalError) terminating connection due to administrator command
[Thu Dec 18 21:19:10.701239 2014] [:error] [pid 12342] FATAL:  terminating connection due to administrator command
[Thu Dec 18 21:19:10.701243 2014] [:error] [pid 12342]  'SELECT distros.name AS distros_name \\nFROM distros ORDER BY distros.name \\n LIMIT %(param_1)s OFFSET %(param_2)s' {'param_1': 50, 'param_2': 0}
```

**Comment by ralphbean** [comment]
I tried to duplicate this too and can't.  It looks like it was something temporary going on with the postgres db on anitya-backend01.

I'm going to close since we don't have any leads.

**Comment by ralphbean** [comment]
Nevermind.  I hit it again on a random different page:  https://release-monitoring.org/projects/search/?pattern=qm-dsp

Same traceback.

**Comment by ralphbean** [comment]
Perhaps this is because a single session is created and kept forever?  Perhaps it should be closed and re-opened on each request?

**Comment by pypingou** [comment]
oh, I have some code to do this (close at the end of the request), we should check if it is present in anitya: https://github.com/fedora-infra/pkgdb2/blob/master/pkgdb2/__init__.py#L211

**Comment by ralphbean** [comment]
Yeah, it's right here:  https://github.com/fedora-infra/anitya/blob/master/anitya/app.py#L115-L118

**Comment by pypingou** [comment]
dang :(
